{{- include "ffc-helm-library.container-secret" (list . "ffc-demo-web.container-secret") -}}
{{- define "ffc-demo-web.container-secret" -}}
stringData:
  {{- if .Values.appInsights.key }}
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ quote .Values.appInsights.key }}
  {{- end }}
  COOKIE_PASSWORD: {{ .Values.container.cookiePassword | quote }}
  {{- if .Values.okta.domain }}
  OKTA_AUTH_SERVER_ID: {{ .Values.okta.authorizationServerId | quote }}
  OKTA_CLIENT_ID: {{ .Values.okta.clientId | quote }}
  OKTA_CLIENT_SECRET: {{ .Values.okta.clientSecret | quote }}
  {{- end }}
  REDIS_PASSWORD: {{ .Values.container.redisPassword | quote }}
{{- end -}}
